---
version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Create version.json
          command: |
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json
      - setup_remote_docker
      - run:
          name: Build
          command: |
            ls
            pwd
            docker info
            docker build -t app:build .
      - run:
          name: Test
          command: |
            docker run -it --rm --entrypoint=/usr/local/bin/php app:build '-i'
      - run:
          name: Push
          command: |
            cat << EOF
            CIRCLE_PROJECT_REPONAME : ${CIRCLE_PROJECT_REPONAME}
            CIRCLE_TAG : ${CIRCLE_TAG}
            CIRCLE_BRANCH : ${CIRCLE_BRANCH}
            EOF

            export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:upgrade-to-v7"

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag app:build mozilla/testrail:upgrade-to-v7
            docker push mozilla/testrail:upgrade-to-v7
      - store_artifacts:
          path: version.json
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
