---
version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Create version.json
          command: |
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json
      - setup_remote_docker
      - run:
          name: Build
          command: |
            ls
            pwd
            docker info
            docker build --progress plain -t app:build .
      - run:
          name: Test
          command: |
            docker run -it --rm --entrypoint=/usr/local/bin/php app:build '-i'
      - run:
          name: Push
          command: |
            cat << EOF
            CIRCLE_PROJECT_REPONAME : ${CIRCLE_PROJECT_REPONAME}
            CIRCLE_TAG : ${CIRCLE_TAG}
            CIRCLE_BRANCH : ${CIRCLE_BRANCH}
            EOF

            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_IMAGE="mozilla/testrail:${CIRCLE_TAG}"
            elif [ "${CIRCLE_BRANCH}" = "master" ]; then
              DOCKER_IMAGE="mozilla/testrail:latest"
            else
              DOCKER_IMAGE="mozilla/testrail:${CIRCLE_BRANCH}"
            fi

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag app:build ${DOCKER_IMAGE}
            docker push ${DOCKER_IMAGE}

      - store_artifacts:
          path: version.json
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
